### ISSUE TITLE
Connection list update

### ISSUE THREAD

**Issue by sorlac** [1dl3/graph#8]
Sorry :)

Connection list does not update values when changing the scaling
Reaction rates in unscaled case are not depicted with 3 significant digits.

**Comment by 1dl3** [comment]
"Reaction rates in unscaled case are not depicted with 3 significant digits"  can't reproduce

**Comment by sorlac** [comment]
ah da hab ich mich falsch ausgedrueckt: 
es sollten 3 ziffern da stehen die nicht 0 sind. 
wenn die daten gescaled sind ist das einfach weils immer die 3 stellen hinter dem komma sind.
bei den nichtnormalisierten daten ist das anders. da werden einige als 0.001 oder 0.000 angezeigt obwohl sie eigentlich 0.00135 bzw 0.000234 sein sollten.

**Comment by 1dl3** [comment]
kann dir nummer auch gerundet werden statt 0.00251567390276147 => 0.002516
nehm aber amal an das das keine option ist :D

**Comment by sorlac** [comment]
Hmm, lieber waer mir anders, aber wenns gar nicht geht dann so.

On 15/06/15 17:05, Benedikt Fuisz wrote:

> kann dir nummer auch gerundet werden statt 0.00251567390276147 => 0.002516
> nehm aber amal an das das keine option ist :D
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/1dl3/graph/issues/8#issuecomment-112120988.

## 

Dr. Markus Keller
Ralser Group
University of Cambridge
Department of Biochemistry
Cambridge CB2 1GA
United Kingdom
mk747@cam.ac.uk
